import type { ClassDef, FlagDef, GrenadeDef, GrenadeId, TeamDef, WeaponDef } from './types'

export const MAP = {
  size: 420,
  half: 210,
  terrainSegments: 140,
  heightScale: 9,
  waterLevel: -1.2,
  fogNear: 90,
  fogFar: 330,
} as const

export const THEME = {
  sky: 0x9fc6e8,
  fog: 0xb7cfe0,
  sun: 0xfff2d6,
  ambientSky: 0xbfd8ff,
  ambientGround: 0x6b7a4a,
  grass: 0x6b9a3f,
  grassDark: 0x4f7b30,
  dirt: 0x9c7b52,
  rock: 0x8a8a86,
  sand: 0xd6c48f,
  water: 0x3f7fa8,
  tree: 0x3d7a33,
  trunk: 0x6b4a2b,
  building: 0xcfc6b3,
  roof: 0x8b4a3a,
  metal: 0x7d848c,
  tracer: 0xffe08a,
  blood: 0xe03030,
  hud: '#f2f2f2',
  hudDim: 'rgba(242,242,242,0.6)',
  hudBg: 'rgba(10,14,20,0.55)',
  accent: '#ffb347',
} as const

export const TEAMS: readonly TeamDef[] = [
  {
    id: 'blue',
    name: 'The Chatterbox Corps',
    shortName: 'CHATTER',
    colour: 0x3f7fd6,
    css: '#5aa0ff',
    hq: { x: -185, z: -160 },
  },
  {
    id: 'orange',
    name: 'The Mumbling Militia',
    shortName: 'MUMBLE',
    colour: 0xe0782a,
    css: '#ff9a3c',
    hq: { x: 185, z: 160 },
  },
]

export const FLAGS: readonly FlagDef[] = [
  // Point-symmetric about the roundabout so neither HQ has a shorter walk to its second flag.
  { id: 'a', letter: 'A', name: 'The Pub', x: -125, z: -82, radius: 14 },
  { id: 'b', letter: 'B', name: 'Bus Stop', x: -30, z: 90, radius: 12 },
  { id: 'c', letter: 'C', name: 'The Roundabout', x: 0, z: 0, radius: 16 },
  { id: 'd', letter: 'D', name: 'Bunnings', x: 30, z: -90, radius: 15 },
  { id: 'e', letter: 'E', name: 'The Servo', x: 125, z: 82, radius: 13 },
]

export const WEAPONS: Readonly<Record<string, WeaponDef>> = {
  chattergun: {
    id: 'chattergun',
    name: 'Chatter-Gun SMG',
    blurb: 'Says a lot, very quickly, mostly up close.',
    kind: 'hitscan',
    damage: 20,
    headshotMultiplier: 1.8,
    rpm: 800,
    magSize: 32,
    reserveMags: 6,
    reloadTime: 1.6,
    spread: 0.014,
    adsSpread: 0.005,
    bloomPerShot: 0.0035,
    bloomMax: 0.03,
    recoil: 0.009,
    recoilSide: 0.5,
    range: 120,
    falloffStart: 18,
    falloffEnd: 55,
    minDamageMul: 0.5,
    moveSpeed: 7.2,
    auto: true,
    pellets: 1,
    adsFov: 55,
    tracerColour: 0xffe08a,
    sound: 'smg',
    stats: { damage: 0.35, rate: 0.95, range: 0.3, control: 0.7 },
  },
  talkingpoint: {
    id: 'talkingpoint',
    name: 'Talking Point Rifle',
    blurb: 'Balanced, sensible, and nobody remembers picking it.',
    kind: 'hitscan',
    damage: 26,
    headshotMultiplier: 2,
    rpm: 600,
    magSize: 30,
    reserveMags: 5,
    reloadTime: 2,
    spread: 0.011,
    adsSpread: 0.003,
    bloomPerShot: 0.0025,
    bloomMax: 0.022,
    recoil: 0.014,
    recoilSide: 0.35,
    range: 220,
    falloffStart: 35,
    falloffEnd: 100,
    minDamageMul: 0.65,
    moveSpeed: 6.6,
    auto: true,
    pellets: 1,
    adsFov: 50,
    tracerColour: 0xffe08a,
    sound: 'rifle',
    stats: { damage: 0.5, rate: 0.7, range: 0.6, control: 0.6 },
  },
  monologue: {
    id: 'monologue',
    name: 'Monologue LMG',
    blurb: 'A 100 round magazine and absolutely no editing. Kicks like an opinion.',
    kind: 'hitscan',
    damage: 24,
    headshotMultiplier: 1.8,
    rpm: 620,
    magSize: 100,
    reserveMags: 3,
    reloadTime: 4.2,
    spread: 0.02,
    adsSpread: 0.006,
    bloomPerShot: 0.002,
    bloomMax: 0.028,
    recoil: 0.02,
    recoilSide: 0.6,
    range: 250,
    falloffStart: 45,
    falloffEnd: 130,
    minDamageMul: 0.7,
    moveSpeed: 6,
    auto: true,
    pellets: 1,
    adsFov: 58,
    tracerColour: 0xffc060,
    sound: 'lmg',
    stats: { damage: 0.45, rate: 0.75, range: 0.7, control: 0.3 },
  },
  interruption: {
    id: 'interruption',
    name: 'Interruption Shotgun',
    blurb: 'Ends the conversation inside ten metres. Useless past twenty.',
    kind: 'hitscan',
    damage: 13,
    headshotMultiplier: 1.3,
    rpm: 85,
    magSize: 6,
    reserveMags: 5,
    reloadTime: 2.6,
    spread: 0.055,
    adsSpread: 0.045,
    bloomPerShot: 0,
    bloomMax: 0,
    recoil: 0.05,
    recoilSide: 0.2,
    range: 60,
    falloffStart: 7,
    falloffEnd: 24,
    minDamageMul: 0.15,
    moveSpeed: 6.8,
    auto: false,
    pellets: 9,
    adsFov: 62,
    tracerColour: 0xffd090,
    sound: 'shotgun',
    stats: { damage: 0.95, rate: 0.15, range: 0.1, control: 0.4 },
  },
  pointmaker: {
    id: 'pointmaker',
    name: 'Point-Maker Rifle',
    blurb: 'Makes one very good point from a very long way away.',
    kind: 'hitscan',
    damage: 90,
    headshotMultiplier: 2.5,
    rpm: 45,
    magSize: 5,
    reserveMags: 8,
    reloadTime: 2.8,
    spread: 0.04,
    adsSpread: 0.0006,
    bloomPerShot: 0.02,
    bloomMax: 0.04,
    recoil: 0.06,
    recoilSide: 0.25,
    range: 600,
    falloffStart: 600,
    falloffEnd: 600,
    minDamageMul: 1,
    moveSpeed: 6.4,
    auto: false,
    pellets: 1,
    adsFov: 18,
    tracerColour: 0xffffff,
    sound: 'sniper',
    stats: { damage: 0.9, rate: 0.1, range: 1, control: 0.2 },
  },
  rebuttal: {
    id: 'rebuttal',
    name: 'Rebuttal Launcher',
    blurb: '"Well, actually..." at 55 metres per second. Also opens Utes.',
    kind: 'rocket',
    damage: 120,
    headshotMultiplier: 1,
    rpm: 30,
    magSize: 1,
    reserveMags: 4,
    reloadTime: 3,
    spread: 0.004,
    adsSpread: 0.002,
    bloomPerShot: 0,
    bloomMax: 0,
    recoil: 0.08,
    recoilSide: 0.3,
    range: 400,
    falloffStart: 400,
    falloffEnd: 400,
    minDamageMul: 1,
    moveSpeed: 6.2,
    auto: false,
    pellets: 1,
    adsFov: 50,
    tracerColour: 0xff8040,
    sound: 'rocket',
    stats: { damage: 1, rate: 0.05, range: 0.8, control: 0.3 },
  },
  sidebar: {
    id: 'sidebar',
    name: 'Sidebar Pistol',
    blurb: 'For when the main point runs dry.',
    kind: 'hitscan',
    damage: 26,
    headshotMultiplier: 2,
    rpm: 340,
    magSize: 12,
    reserveMags: 5,
    reloadTime: 1.3,
    spread: 0.012,
    adsSpread: 0.005,
    bloomPerShot: 0.006,
    bloomMax: 0.03,
    recoil: 0.03,
    recoilSide: 0.4,
    range: 80,
    falloffStart: 15,
    falloffEnd: 45,
    minDamageMul: 0.5,
    moveSpeed: 6.8,
    auto: false,
    pellets: 1,
    adsFov: 60,
    tracerColour: 0xffe08a,
    sound: 'pistol',
    stats: { damage: 0.4, rate: 0.4, range: 0.25, control: 0.6 },
  },
}

/** Primaries offered on the loadout screen, in display order. */
export const PRIMARIES: readonly string[] = ['chattergun', 'talkingpoint', 'monologue', 'interruption', 'pointmaker', 'rebuttal']

/** Multipliers on the spread cone by stance. Bloom decays exponentially at bloomDecay per second. */
export const AIM = {
  movingHip: 1.6,
  movingAds: 1.25,
  crouch: 0.7,
  airborne: 2.2,
  bloomDecay: 6,
  /** Fraction of each kick the view settles back by, and how fast, once the trigger is released. */
  recoilRecovery: 0.7,
  recoilRecoverRate: 10,
} as const

export const GRENADES: Readonly<Record<GrenadeId, GrenadeDef>> = {
  hotTake: {
    id: 'hotTake',
    name: 'Hot Take',
    blurb: 'Cook it, lob it, wait three seconds for the fallout.',
    kind: 'frag',
    count: 2,
    fuse: 3.2,
    throwSpeed: 17,
    radius: 7,
    damage: 110,
    bounce: 0.35,
    colour: 0x3a4a2a,
  },
  micDrop: {
    id: 'micDrop',
    name: 'Mic Drop',
    blurb: 'Goes off on contact. Smaller blast, no arguing with it.',
    kind: 'impact',
    count: 2,
    fuse: 6,
    throwSpeed: 22,
    radius: 4.5,
    damage: 135,
    bounce: 0,
    colour: 0x1a1a1a,
  },
  awkwardSilence: {
    id: 'awkwardSilence',
    name: 'Awkward Silence',
    blurb: 'Nobody near it can aim, speak or think for a few seconds.',
    kind: 'stun',
    count: 2,
    fuse: 2.2,
    throwSpeed: 17,
    radius: 10,
    damage: 8,
    bounce: 0.4,
    colour: 0xeeeeee,
  },
}

export const CLASSES: readonly ClassDef[] = [
  { id: 'yapper', name: 'Yapper', blurb: 'Fast talker, faster runner.', loadout: { primary: 'chattergun', secondary: 'sidebar', grenade: 'hotTake' } },
  { id: 'debater', name: 'Debater', blurb: 'Structured, mid-range, insufferable.', loadout: { primary: 'talkingpoint', secondary: 'sidebar', grenade: 'micDrop' } },
  { id: 'podcaster', name: 'Podcaster', blurb: 'Will not stop.', loadout: { primary: 'monologue', secondary: 'sidebar', grenade: 'hotTake' } },
  { id: 'heckler', name: 'Heckler', blurb: 'Gets right up in your face.', loadout: { primary: 'interruption', secondary: 'sidebar', grenade: 'awkwardSilence' } },
  { id: 'lecturer', name: 'Lecturer', blurb: 'One point, from very far away.', loadout: { primary: 'pointmaker', secondary: 'sidebar', grenade: 'hotTake' } },
  { id: 'mechanic', name: 'Mechanic', blurb: '"Well, actually..." with a launcher.', loadout: { primary: 'rebuttal', secondary: 'sidebar', grenade: 'micDrop' } },
]

export const MATCH = {
  startTickets: 250,
  bleedPerSecondPerFlag: 0.35,
  ticketPerDeath: 1,
  botsPerTeam: 11,
  respawnDelay: 4,
  captureSeconds: 10,
  scoreKill: 100,
  scoreHeadshot: 25,
  scoreTeamKill: 50,
  scoreCapture: 200,
  scoreDefend: 50,
  scoreAssist: 50,
} as const

export const SOLDIER = {
  maxHealth: 100,
  regenDelay: 4,
  regenRate: 22,
  eyeHeight: 1.62,
  crouchEyeHeight: 1.05,
  radius: 0.45,
  height: 1.8,
  gravity: 24,
  jumpSpeed: 7.5,
  sprintMultiplier: 1.42,
  crouchMultiplier: 0.55,
  fallDamageSpeed: 14,
} as const

export const VEHICLE = {
  name: 'The Ute',
  maxHealth: 400,
  maxSpeed: 26,
  accel: 14,
  brake: 24,
  reverseSpeed: 9,
  steerRate: 1.9,
  drag: 0.4,
  roadkillSpeed: 6,
  respawnDelay: 25,
  seats: 1,
} as const


export const ROCKET = {
  speed: 55,
  radius: 5.5,
  gravity: 3,
  lifetime: 8,
} as const

export const LEVOLUTION = {
  towerX: 60,
  towerZ: -60,
  hp: 900,
  radius: 11,
  damage: 200,
} as const
